package com.remote_plugin.xuancao.remoteplugin.db.bean;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER_INFO_DB".
 */
@Entity
public class UserInfoDB implements Parcelable {
    private String user_id;
    private String nick_name;
    private String birthday;
    private String avatar;
    private String gender;
    private String mobile;

    @Override
    public String toString() {
        return "UserInfoDB{" +
                "user_id='" + user_id + '\'' +
                ", nick_name='" + nick_name + '\'' +
                ", birthday='" + birthday + '\'' +
                ", avatar='" + avatar + '\'' +
                ", gender='" + gender + '\'' +
                ", mobile='" + mobile + '\'' +
                '}';
    }

    @Generated
    public UserInfoDB() {
    }

    @Generated
    public UserInfoDB(String user_id, String nick_name, String birthday, String avatar, String gender, String mobile) {
        this.user_id = user_id;
        this.nick_name = nick_name;
        this.birthday = birthday;
        this.avatar = avatar;
        this.gender = gender;
        this.mobile = mobile;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.user_id);
        dest.writeString(this.nick_name);
        dest.writeString(this.birthday);
        dest.writeString(this.avatar);
        dest.writeString(this.gender);
        dest.writeString(this.mobile);
    }

    protected UserInfoDB(Parcel in) {
        this.user_id = in.readString();
        this.nick_name = in.readString();
        this.birthday = in.readString();
        this.avatar = in.readString();
        this.gender = in.readString();
        this.mobile = in.readString();
    }

    public static final Parcelable.Creator<UserInfoDB> CREATOR = new Parcelable.Creator<UserInfoDB>() {
        @Override
        public UserInfoDB createFromParcel(Parcel source) {
            return new UserInfoDB(source);
        }

        @Override
        public UserInfoDB[] newArray(int size) {
            return new UserInfoDB[size];
        }
    };
}
