package com.virtual.xuancao.virtualapkprogram.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.virtual.xuancao.virtualapkprogram.db.bean.UserInfoDB;

import com.virtual.xuancao.virtualapkprogram.db.dao.UserInfoDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDBDaoConfig;

    private final UserInfoDBDao userInfoDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDBDaoConfig = daoConfigMap.get(UserInfoDBDao.class).clone();
        userInfoDBDaoConfig.initIdentityScope(type);

        userInfoDBDao = new UserInfoDBDao(userInfoDBDaoConfig, this);

        registerDao(UserInfoDB.class, userInfoDBDao);
    }
    
    public void clear() {
        userInfoDBDaoConfig.clearIdentityScope();
    }

    public UserInfoDBDao getUserInfoDBDao() {
        return userInfoDBDao;
    }

}
